<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-1KOV8VAE" failures="0" tests="9" name="qaautomation.august2021.APITest" time="0.022" errors="1" timestamp="01 Oct 2021 05:43:44 GMT" skipped="8">
  <testcase classname="qaautomation.august2021.APITest" name="dashboardAPIWithSchema" time="0.000">
    <skipped/>
  </testcase> <!-- dashboardAPIWithSchema -->
  <testcase classname="qaautomation.august2021.APITest" name="configAPI" time="0.000">
    <skipped/>
  </testcase> <!-- configAPI -->
  <testcase classname="qaautomation.august2021.APITest" name="signup" time="0.000">
    <skipped/>
  </testcase> <!-- signup -->
  <testcase classname="qaautomation.august2021.APITest" name="incorrectLoginAPI" time="0.000">
    <skipped/>
  </testcase> <!-- incorrectLoginAPI -->
  <testcase classname="qaautomation.august2021.APITest" name="fakerEmail" time="0.000">
    <skipped/>
  </testcase> <!-- fakerEmail -->
  <testcase classname="qaautomation.august2021.APITest" name="configAPI2" time="0.000">
    <skipped/>
  </testcase> <!-- configAPI2 -->
  <testcase classname="qaautomation.august2021.APITest" name="testLoginAPI" time="0.022">
    <error type="java.lang.ExceptionInInitializerError">
      <![CDATA[java.lang.ExceptionInInitializerError
at qaautomation.august2021.BaseAPITest.testLoginAPI(BaseAPITest.java:24)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:401)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
at qaautomation.august2021.utils.DataUtility.<clinit>(DataUtility.java:23)
... 21 more
]]>
    </error>
  </testcase> <!-- testLoginAPI -->
  <testcase classname="qaautomation.august2021.APITest" name="userAPI" time="0.000">
    <skipped/>
  </testcase> <!-- userAPI -->
  <testcase classname="qaautomation.august2021.APITest" name="dashboardAPI" time="0.000">
    <skipped/>
  </testcase> <!-- dashboardAPI -->
</testsuite> <!-- qaautomation.august2021.APITest -->
